
irint("Hello NYC")
print("Hello NYC")
print("Hello NYC")
print("Hello NYC")
print("Ola Mira")
print("Ola Mira")
print("Ola Mira")
print("Ola Mira")
print("Ola Mira")
print("Ola Mira")
print("Ola Mira")
print("Ola Mira")
